### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by venterlin** [luklanis/csipsimple-plugin#1]
Thanks for creating a plugin for the CSipSimple/Tasker intents.

I have a few questions.

Does this plugin still work, and more specifically does it work with Kit-Kat and the latest CSipSimple client?

In the repository notes, you state this needs to work with a specific locale library. Is that library still available, and does this plugin need to be built with it in order to work?

I tried the APK found in the zip download. It installs, but crashes in Kit-Kat. I'm assuming it either needs to be built with a locale library or is incompatible.

Thanks for any help.

**Comment by luklanis** [comment]
Hi,

Thanks for trying the plugin and sorry for the late response.
Until now, I didn't test it on kit-kat, but the needed library should still be available on http://www.twofortyfouram.com/developer.html

I'l try to go into this today.

**Comment by luklanis** [comment]
Hi,

Sorry for the late response!

The plugin works again in Kit-Kat. Unfortunately, github hasn't a download section anymore. If you'd like to try it, you can download the apk from https://www.wuala.com/gulb/open/CSIPSimplePlugin/csipsimple-plugin-release.apk

Cheers
